export const EconomyConfig = {
    BALL_BASE_COST: 1,

    AUTO_DROPPER_BASE_COST: 25,
    AUTO_DROPPER_COST_MULT: 2.5,

    MULTIPLIER_BASE_COST: 50,
    MULTIPLIER_COST_MULT: 2.0,

    BALL_CAPACITY_BASE_COST: 75,
    BALL_CAPACITY_COST_MULT: 1.8,

    GOLDEN_BALL_BASE_COST: 250,
    GOLDEN_BALL_COST_MULT: 1.8,

    LUCKY_PEG_BASE_COST: 500,
    LUCKY_PEG_COST_MULT: 2.0,

    SPEED_BASE_COST: 400,
    SPEED_COST_MULT: 1.9,

    DOUBLE_STRIKE_BASE_COST: 800,
    DOUBLE_STRIKE_COST_MULT: 2.1,

    INSURANCE_BASE_COST: 350,
    INSURANCE_COST_MULT: 1.9,

    BANK_BASE_COST: 1200,
    BANK_COST_MULT: 2.2,
};
