export const EconomyConfig = {

    BALL_COST: 1,

    BALL_SPAWN_COOLDOWN_MS: 280,

    MIN_SPAWN_COOLDOWN_MS: 110,

    AUTO_SAVE_INTERVAL_MS: 5000,

    OFFLINE_MIN_SECONDS: 30,

    OFFLINE_MAX_SECONDS: 8 * 60 * 60,

    /** Tab background catch-up uses same cap as offline. */
    BACKGROUND_MAX_SECONDS: 8 * 60 * 60,

    AUTO_DROPPER_BASE_COST: 12,
    AUTO_DROPPER_COST_MULT: 1.58,

    MULTIPLIER_BASE_COST: 40,
    MULTIPLIER_COST_MULT: 1.28,

    BALL_CAPACITY_BASE_COST: 45,
    BALL_CAPACITY_COST_MULT: 1.48,
    BALL_CAPACITY_BASE: 12,
    BALL_CAPACITY_PER_LEVEL: 3,

    GOLDEN_BALL_BASE_COST: 180,
    GOLDEN_BALL_COST_MULT: 1.42,
    GOLDEN_BALL_MAX_CHANCE: 45,
    GOLDEN_BALL_REWARD_MULT: 4.5,

    LUCKY_PEG_BASE_COST: 85,
    LUCKY_PEG_COST_MULT: 1.38,
    LUCKY_PEG_CHANCE_PER_LEVEL: 3,
    LUCKY_PEG_MAX_CHANCE: 36,
    LUCKY_PEG_MAX_LEVEL_FOR_CHANCE: 12,
    LUCKY_PEG_BASE_BONUS: 2.5,
    LUCKY_PEG_OVERLEVEL_BONUS_MULT: 0.1,
    PEG_HIT_COOLDOWN_MS: 100,

    SPEED_BOOST_BASE_COST: 70,
    SPEED_BOOST_COST_MULT: 1.4,
    SPEED_BOOST_MS_PER_LEVEL: 20,
    SPEED_BOOST_OVERLEVEL_AUTO_MULT: 0.04,

    COMBO_WINDOW_MS: 2800,
    COMBO_BONUS_PER_STACK: 0.045,
    COMBO_MAX_STACK: 15,

    DAILY_BONUS_BASE: 75,
    DAILY_BONUS_SCALE: 0.12,
    DAILY_STREAK_BONUS: 0.12,
    DAILY_STREAK_CAP: 21
};
